### ISSUE TITLE
More/standardized function descriptions

### ISSUE THREAD

**Issue by ghost** [aisapatino/flamingloot-ml#27]
Format I'm thinking of
```
function flsys:AFunction()
--- Function summary
-- params if needed
-- called by: flsys:MainFunc
-- calls: flsys:OtherFunc
```

**Comment by aisapatino** [comment]
I don't think called by / called is a great idea since it's likely to get outdated. `ag`/`grep` makes this easier, and beyond that it calls for a restructure of code if it's that hard to follow.
